// <auto-generated />
namespace Ember_Contact_Management_WebAPI.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class contact_data_annotation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(contact_data_annotation));
        
        string IMigrationMetadata.Id
        {
            get { return "201303202234520_contact_data_annotation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
